#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Spring Default Setup
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# name : project name
# rabbitmq : rabbitMq Setup
# jps : jpa setup
#
spring:
  application:
    name: customer-service
  rabbitmq:
    host: ${RABBITMQ_SERVER_URL:localhost}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    sql-script-encoding: UTF-8
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:customer;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Feign Setup
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Hystrix Setup
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
