spring:
  application:
    name: order-service

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Feign Options
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

coe:
  application:
    customer-service: CUSTOMER-SERVICE

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Endpoint output options for Hystrix Stream
#----------------------------------------------------------------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always
